services:
  my-service:
    build:
      context: ./my-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      #- SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    depends_on:
      - consul-importer
      - consul-dev
    networks:
      - baeldung-spring-cloud-consul
  discovery-client-service:
    build:
      context: ./discovery-client-service
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      #- SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    depends_on:
      - consul-importer
      - consul-dev
    networks:
      - baeldung-spring-cloud-consul
  consul-importer:
    build:
      context: ./docker/consul
      dockerfile: Dockerfile
    depends_on:
      - consul-dev
    #volumes:
    #- ./docker/consul/consul-kv-docker.json:/usr/src/consul/consul-kv-docker.json
    networks:
      - baeldung-spring-cloud-consul
  consul-dev:
    image: hashicorp/consul
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "agent -dev -node=baeldung-spring-cloud-consul -client=0.0.0.0 -log-level=INFO"
    networks:
      - baeldung-spring-cloud-consul

networks:
  baeldung-spring-cloud-consul:
    driver: bridge
